# Aggregations: Min, Max, and Everything In Between

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
sum(L) - np.sum(L)

1.4210854715202004e-14

## Summing the Values in an Array
NumPy's version of the operation is computed much more quickly:

In [10]:
L = np.random.random(100000)

%timeit sum(L)
%timeit np.sum(L) 

8.74 ms ± 579 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
51.2 µs ± 3.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [11]:
%timeit min(L)
%timeit np.min(L)

5.8 ms ± 32.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
36.7 µs ± 487 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Multi dimensional aggregates¶
One common type of aggregation operation is an aggregate along a row or column

In [15]:
M = np.random.random((3,4))
M

array([[0.18759324, 0.4129695 , 0.89336597, 0.95592558],
       [0.95303382, 0.49889876, 0.91273806, 0.19436668],
       [0.42712312, 0.04950768, 0.61877168, 0.45365815]])

for a bi-dimensional array returns the aggregate over the entire array --> max min

In [40]:
M.max(), '  ', M.sum(), '  ', np.add.reduce(M),'  ', np.add.reduce(M,axis=1)

(0.9559255770700871,
 '  ',
 6.557952225971362,
 '  ',
 array([1.56775018, 0.96137593, 2.42487571, 1.60395041]),
 '  ',
 array([2.44985428, 2.55903732, 1.54906063]))

#### REMINDER of computations and aggregates (previous notebook)
- How can I reproduce the .sum() of multi-dimensional, aggregating add ?
- add.accumulate(axix=0) adds elements along vertical axis returning **partial** sums
- add.reduce(axix=0) adds elements along vertical axis returning the **final** sums

In [46]:
M.sum(),'  ', np.add.accumulate(M),  '  ', np.add.reduce(M),  '  ', np.add.reduce(M,axis=1)

(6.557952225971362,
 '  ',
 array([[0.18759324, 0.4129695 , 0.89336597, 0.95592558],
        [1.14062706, 0.91186825, 1.80610402, 1.15029226],
        [1.56775018, 0.96137593, 2.42487571, 1.60395041]]),
 '  ',
 array([1.56775018, 0.96137593, 2.42487571, 1.60395041]),
 '  ',
 array([2.44985428, 2.55903732, 1.54906063]))

- you can reproduce the .sum() by reducing twice

In [45]:
%timeit M.sum()
%timeit np.add.reduce(np.add.reduce(M))

3.08 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
3.15 µs ± 36.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. 

In [52]:
M.sum(axis=0), 'which is the same as', np.add.reduce(M)

(array([1.56775018, 0.96137593, 2.42487571, 1.60395041]),
 'which is the same as',
 array([1.56775018, 0.96137593, 2.42487571, 1.60395041]))

### Other aggregation functions

In [55]:
M.prod(), '   ', M.prod(axis=1)

(3.312547813898632e-05, '   ', array([0.06615896, 0.0843507 , 0.00593588]))

In [56]:
M.std()

0.3075912583723385

In [57]:
M.argmin()

9