In [13]:
import numpy as np
generator = np.random.RandomState(150777)

In [14]:
x = generator.randint(100,size=10)
x

array([14, 59, 54, 88, 89, 12, 72,  4, 62, 22])

In [15]:
([x[3], x[7], x[2]]),type([x[3], x[7], x[2]])

([88, 4, 54], list)

In [16]:
indices = [3,7,2]
x[indices],type(x)

(array([88,  4, 54]), numpy.ndarray)

### fancy indexing basics
When using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed:

In [17]:
indices_matrix = generator.randint?

In [25]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html
indices_matrix = generator.randint(0,10,size=12).reshape((4,3))
indices_matrix

array([[2, 4, 6],
       [2, 1, 3],
       [7, 9, 6],
       [7, 0, 6]])

In [23]:
x[indices_matrix]

array([[54, 62, 72],
       [14, 59, 88],
       [89, 72, 72],
       [14, 72, 59]])

Fancy indexing also works in multiple dimensions. Consider the following array:


In [34]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
row = np.array([0,1,2])
col = np.array([2,1,3])
X[row,col]

array([ 2,  5, 11])

In [42]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [39]:
# broadcasting
row[:,np.newaxis]+col

array([[2, 1, 3],
       [3, 2, 4],
       [4, 3, 5]])

In [41]:
X[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [43]:
(row[:,np.newaxis]+col).shape

(3, 3)

In [52]:
np.identity((row[:,np.newaxis]+col).shape[0])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
(row[:,np.newaxis])*np.ones((row[:,np.newaxis]+col).shape[0])

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [64]:
np.ones((row[:,np.newaxis]+col).shape[0])[:,np.newaxis]

array([[1.],
       [1.],
       [1.]])

In [65]:
col*np.ones((row[:,np.newaxis]+col).shape[0])[:,np.newaxis]

array([[2., 1., 3.],
       [2., 1., 3.],
       [2., 1., 3.]])

In [176]:
def show_broadcasted_arrays(a,b):
    make_broadcast = a+b
    print(make_broadcast)
    dim_0 = make_broadcast.shape[0]
    dim_1 = make_broadcast.shape[1]

    print('shape of broadcast is: %d %d\n'%(dim_0,dim_1))
    
    print(a)
    print(a*np.ones(dim_0)[:,np.newaxis])
    #print (np.ones(a.shape[0])[:,np.newaxis]  )
    #print (np.ones(a.shape[0])[:,np.newaxis]*a  )
    #print ((a[:,np.newaxis]) * np.ones((a[np.newaxis,:]+b).shape[0]) )
    print()
    print(b)
    print(np.ones(dim_1)[np.newaxis,:]*b)
    print()
    #print (b*np.ones((a[:,np.newaxis]+b).shape[0])[:,np.newaxis])
    #print (b*np.ones(b.shape[0])[np.newaxis,:]   ) 
    
    print(make_broadcast)
    return 0

In [179]:
# ok
a = np.array([99,100])
b = col[:,np.newaxis]

#a = 1
#b = np.arange(3)

show_broadcasted_arrays(a,b)

[[101 102]
 [100 101]
 [102 103]]
shape of broadcast is: 3 2

[ 99 100]
[[ 99. 100.]
 [ 99. 100.]
 [ 99. 100.]]

[[2]
 [1]
 [3]]
[[2. 2.]
 [1. 1.]
 [3. 3.]]

[[101 102]
 [100 101]
 [102 103]]


0

In [226]:
#x = np.array([[1], [2], [3]])
#y = np.array([4, 5, 6])

# x = 1
# y = np.arange(3)

# y = np.arange(15).reshape(5,3)
# x = np.arange(3)

# x = np.arange(5)
# y = np.arange(5)[:,np.newaxis]

y = np.arange(10).reshape(5,2)
x = np.arange(5)[:,np.newaxis]

In [232]:
def show_broadcasted_arrays(x,y):
    b = np.broadcast(y,x)
    out = np.ones(b.shape)
    
    print('\n\n%s\n\n gets broadcast to:\n'%x)
    print(x*out)
    print()
    print('\n\n%s\n\n gets broadcast to:\n'%y)
    print(y*out)
    print()

show_broadcasted_arrays(x,y)



[[0]
 [1]
 [2]
 [3]
 [4]]

 gets broadcast to:

[[0. 0.]
 [1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]]



[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 gets broadcast to:

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]

