## Standard arrays are pyhon built in

In [1]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## However numpy package is more powerful

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

# help(np.random.randint)

In [3]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional arraypy as np

In [4]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [5]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


# Slicing (standard)
Slicing identifies ranges using index starting at 0 [min:max),
i.e. top bound is not included

In [6]:
x1[::]

array([5, 0, 3, 3, 7, 9])

In [7]:
print(x1[0], x1[0:], x1[0:1], x1[0:2],)

5 [5 0 3 3 7 9] [5] [5 0]


In [8]:
x3[1:3,2:4,3:5]

array([[[4, 5],
        [4, 1]],

       [[3, 5],
        [6, 4]]])

In [9]:
x3[::-1,::,::]

array([[[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]]])

# Subarrays as no-copy views
One important–and extremely useful–thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
sub_x2 = x2[0:2,0:4:2]
print(sub_x2)

[[3 2]
 [7 8]]


In [12]:
sub_x2[1,1]=150777

In [13]:
x2

array([[     3,      5,      2,      4],
       [     7,      6, 150777,      8],
       [     1,      6,      7,      7]])

# Reshaping
Where possible, the reshape method will use a *no-copy view* of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the *conversion of a one-dimensional array into a two-dimensional row or column matrix*. This can be done with the reshape method, or more easily done by making use of the newaxis keyword within a slice operation:

In [14]:
half_unit_ste = np.arange(0,10,0.5)
half_unit_ste

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [15]:
half_unit_ste.reshape(4,5)

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5],
       [5. , 5.5, 6. , 6.5, 7. ],
       [7.5, 8. , 8.5, 9. , 9.5]])

In [16]:
rf = np.array([1, 2, 3], dtype=complex)
rf

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
rf.reshape(1,3)

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [18]:
rf.reshape(3,1)

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j]])

good reference to undertand np.newaxis

https://medium.com/@ian.dzindo01/what-is-numpy-newaxis-and-when-to-use-it-8cb61c7ed6ae

In [19]:
rf[np.newaxis, :]

array([[1.+0.j, 2.+0.j, 3.+0.j]])

In [20]:
rf[:, np.newaxis]

array([[1.+0.j],
       [2.+0.j],
       [3.+0.j]])

# Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

''np.concatenate

np.vstack

np.hstack''

In [21]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [22]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [23]:
 dnp.concatenate([grid, grid],axis=1)

NameError: name 'dnp' is not defined

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

In [ ]:
np.hstack([y,grid])

In [ ]:
np.concatenate([y, grid],axis=1)

# Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [1, 7])
print(x1, x2, x3)

In [ ]:
grid = np.arange(16).reshape((4, 4))
print(grid)
upper, lower = np.vsplit(grid, [2])
print('\n after splitting it')
print(upper)
print(lower)

In [ ]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)