In [1]:
import numpy as np

# O(n^2)
def selection_sort(x):
    for u in range(len(x)):
        swap_idx = u + np.argmin(x[u:])
        (x[u], x[swap_idx]) = (x[swap_idx], x[u])
    return x

def selection_sort_copy(x):
    y = x.copy()
    return selection_sort(y)

In [2]:
x = np.array([1,6,4,7,9,5,7,3,2,0])
print(x, ' =>', selection_sort_copy(x))
print(x, ' =>', selection_sort(x))

[1 6 4 7 9 5 7 3 2 0]  => [0 1 2 3 4 5 6 7 7 9]
[0 1 2 3 4 5 6 7 7 9]  => [0 1 2 3 4 5 6 7 7 9]


In [11]:
# compare element-to-element: 
#           [first-to-secondlast] > [second-to-last] 

# when all comparisons are false
#           x_i < x_i+1 for all i's

# hence the array is sorted

def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
        print(x[:-1])
        print(x[1:])
        print((x[:-1] > x[1:]))
        print()
    return x

In [13]:
x = np.array([1,6,4,9,7,])
print(x, ' =>', bogosort(x))

[9 4 7 6]
[4 7 6 1]
[ True False  True  True]

[6 4 1 7]
[4 1 7 9]
[ True  True False False]

[7 1 9 6]
[1 9 6 4]
[ True False  True  True]

[7 9 1 6]
[9 1 6 4]
[False  True False  True]

[7 4 1 6]
[4 1 6 9]
[ True  True False False]

[7 4 9 6]
[4 9 6 1]
[ True False  True  True]

[1 9 4 7]
[9 4 7 6]
[False  True False  True]

[6 1 4 9]
[1 4 9 7]
[ True False False  True]

[4 1 7 6]
[1 7 6 9]
[ True False  True False]

[7 1 4 6]
[1 4 6 9]
[ True False False False]

[6 1 7 4]
[1 7 4 9]
[ True False  True False]

[1 9 7 4]
[9 7 4 6]
[False  True  True False]

[4 9 6 1]
[9 6 1 7]
[False  True  True False]

[6 9 7 4]
[9 7 4 1]
[False  True  True  True]

[6 9 4 7]
[9 4 7 1]
[False  True False  True]

[9 4 6 1]
[4 6 1 7]
[ True False  True False]

[7 9 6 4]
[9 6 4 1]
[False  True  True  True]

[1 7 9 6]
[7 9 6 4]
[False False  True  True]

[1 6 9 7]
[6 9 7 4]
[False False  True  True]

[9 7 4 6]
[7 4 6 1]
[ True  True False  True]

[9 1 7 4]
[1 7 4 6]
[ True False  True False]

[7 1 4 6]
[1 

## Fast Sorting in NumPy: np.sort and np.argsort

Although Python has built-in sort and sorted functions to work with lists, we won't discuss them here because NumPy's np.sort function turns out to be much more efficient and useful for our purposes. By default np.sort uses an [NlogN], quicksort algorithm, though mergesort and heapsort are also available. For most applications, the default quicksort is more than sufficient.

In [20]:
x = np.array([2,1,4,3,5])
print(x,' => ',np.sort(x),'which modified x:',x)

[2 1 4 3 5]  =>  [1 2 3 4 5] which modified x: [2 1 4 3 5]
