In [1]:
import numpy as np

# O(n^2)
def selection_sort(x):
    for u in range(len(x)):
        swap_idx = u + np.argmin(x[u:])
        (x[u], x[swap_idx]) = (x[swap_idx], x[u])
    return x

def selection_sort_copy(x):
    y = x.copy()
    return selection_sort(y)

In [2]:
x = np.array([1,6,4,7,9,5,7,3,2,0])
print(x, ' =>', selection_sort_copy(x))
print(x, ' =>', selection_sort(x))

[1 6 4 7 9 5 7 3 2 0]  => [0 1 2 3 4 5 6 7 7 9]
[0 1 2 3 4 5 6 7 7 9]  => [0 1 2 3 4 5 6 7 7 9]


In [11]:
# compare element-to-element: 
#           [first-to-secondlast] > [second-to-last] 

# when all comparisons are false
#           x_i < x_i+1 for all i's

# hence the array is sorted

def bogosort(x):
    while np.any(x[:-1] > x[1:]):
        np.random.shuffle(x)
        print(x[:-1])
        print(x[1:])
        print((x[:-1] > x[1:]))
        print()
    return x

In [13]:
x = np.array([1,6,4,9,7,])
print(x, ' =>', bogosort(x))

[9 4 7 6]
[4 7 6 1]
[ True False  True  True]

[6 4 1 7]
[4 1 7 9]
[ True  True False False]

[7 1 9 6]
[1 9 6 4]
[ True False  True  True]

[7 9 1 6]
[9 1 6 4]
[False  True False  True]

[7 4 1 6]
[4 1 6 9]
[ True  True False False]

[7 4 9 6]
[4 9 6 1]
[ True False  True  True]

[1 9 4 7]
[9 4 7 6]
[False  True False  True]

[6 1 4 9]
[1 4 9 7]
[ True False False  True]

[4 1 7 6]
[1 7 6 9]
[ True False  True False]

[7 1 4 6]
[1 4 6 9]
[ True False False False]

[6 1 7 4]
[1 7 4 9]
[ True False  True False]

[1 9 7 4]
[9 7 4 6]
[False  True  True False]

[4 9 6 1]
[9 6 1 7]
[False  True  True False]

[6 9 7 4]
[9 7 4 1]
[False  True  True  True]

[6 9 4 7]
[9 4 7 1]
[False  True False  True]

[9 4 6 1]
[4 6 1 7]
[ True False  True False]

[7 9 6 4]
[9 6 4 1]
[False  True  True  True]

[1 7 9 6]
[7 9 6 4]
[False False  True  True]

[1 6 9 7]
[6 9 7 4]
[False False  True  True]

[9 7 4 6]
[7 4 6 1]
[ True  True False  True]

[9 1 7 4]
[1 7 4 6]
[ True False  True False]

[7 1 4 6]
[1 

## Fast Sorting in NumPy: np.sort and np.argsort

Although Python has built-in sort and sorted functions to work with lists, we won't discuss them here because NumPy's np.sort function turns out to be much more efficient and useful for our purposes. By default np.sort uses an [NlogN], quicksort algorithm, though mergesort and heapsort are also available. For most applications, the default quicksort is more than sufficient.

In [22]:
x = np.array([2,1,4,3,5])
print(x,' => ',np.sort(x),'which modified x:',x,'(i.e. worked in-place)')

[2 1 4 3 5]  =>  [1 2 3 4 5] which modified x: [2 1 4 3 5] (i.e. worked in-place)


In [23]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)
print(x[i])
print(x)
print(np.sort(x))
print(x)
print(x.sort())
print(x)

[1 0 3 2 4]
[1 2 3 4 5]
[2 1 4 3 5]
[1 2 3 4 5]
[2 1 4 3 5]
None
[1 2 3 4 5]


## Sorting along rows or columns¶
A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument. For example:

In [28]:
generator = np.random.RandomState(150777)
X = generator.randint(0,10,(4,6))
X

array([[6, 8, 9, 8, 9, 4],
       [6, 4, 1, 4, 9, 4],
       [7, 5, 8, 4, 8, 5],
       [7, 8, 5, 0, 2, 2]])

In [46]:
print(np.sort(X,axis=0), '\n\n',np.sort(X,axis=1)\
      ,'\n\n reverse ordering:\n',-np.sort(-X,axis=1) \
      , '\n\n original unchanged:\n',X)

[[6 4 1 0 2 2]
 [6 5 5 4 8 4]
 [7 8 8 4 9 4]
 [7 8 9 8 9 5]] 

 [[4 6 8 8 9 9]
 [1 4 4 4 6 9]
 [4 5 5 7 8 8]
 [0 2 2 5 7 8]] 

 reverse ordering:
 [[9 9 8 8 6 4]
 [9 6 4 4 4 1]
 [8 8 7 5 5 4]
 [8 7 5 2 2 0]] 

 original unchanged:
 [[6 8 9 8 9 4]
 [6 4 1 4 9 4]
 [7 5 8 4 8 5]
 [7 8 5 0 2 2]]


Keep in mind that this treats each row or column as an independent array, and any relationships between the row or column values will be lost!

In [51]:
print(X.sort(axis=0),'\n\n original affected:\n',X)

None 

 original affected:
 [[6 4 1 0 2 2]
 [6 5 5 4 8 4]
 [7 8 8 4 9 4]
 [7 8 9 8 9 5]]


# Partial Sorts: Partitioning
Sometimes we're not interested in sorting the entire array, but simply want to find the k smallest values in the array. NumPy provides this in the np.partition function. np.partition takes an array and a number K; the result is a new array with the smallest K values to the left of the partition, and the remaining values to the right, in arbitrary order:

In [52]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

Note that the first three values in the resulting array are the three smallest in the array, and the remaining array positions contain the remaining values. Within the two partitions, the elements have arbitrary order.

In [56]:
print('originally X: \n',X,'\n\n partioned: \n',np.partition(X,2,axis=0) )

originally X: 
 [[6 4 1 0 2 2]
 [6 5 5 4 8 4]
 [7 8 8 4 9 4]
 [7 8 9 8 9 5]] 

 partioned: 
 [[6 4 1 0 2 2]
 [6 5 5 4 8 4]
 [7 8 8 4 9 4]
 [7 8 9 8 9 5]]
