In [1]:
import numpy as np
np.random.seed(0)     # reproducibility

def compute_reciprocals(values):
    # Return a new array of given shape and type, without initializing entries.
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [2]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

3.41 s ± 278 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
%timeit (1.0 / big_array)

3.44 ms ± 133 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Ufuncs

Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays.

In [3]:
print(compute_reciprocals(values))
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
np.empty(10)

array([6.91675096e-310, 1.66537514e-316, 6.91675184e-310, 2.29175545e-312,
       2.37151510e-322, 2.37151510e-322, 1.66537751e-316, 4.32296990e-311,
       6.91675184e-310, 2.14321575e-312])

In [6]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [12]:
x = np.arange(3,12).reshape((3, 3))
2 ** x

array([[   8,   16,   32],
       [  64,  128,  256],
       [ 512, 1024, 2048]])

In [17]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("-x     = ", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)
-(0.5*x + 1) ** 2

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


array([-1.  , -2.25, -4.  , -6.25])

Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, the + operator is a wrapper for the add function:

In [20]:
print("x     =",  x)
print("x + 5 =",  np.add(x,5) )
print("x - 5 =",  np.subtract(x, 5) )
print("x * 2 =",  np.multiply(x, 2) )
print("x / 2 =",  np.divide(x,2) )
print("x // 2 =", np.floor_divide(x,2) )  # floor division
print("-x     = ",np.negative(x) )
print("x ** 2 =", np.power(x, 2) )
print("x % 2 =",  np.mod(x,2 ) )

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [24]:
q = np.arange(1,20,2).reshape(2,5)

In [28]:
print("q     =",  q, "\n")
print("q + 5 =",  np.add(q,5), "\n" )
print("q - 5 =",  np.subtract(q, 5), "\n" )
print("q * 2 =",  np.multiply(q, 2), "\n" )
print("q / 2 =",  np.divide(q,2), "\n" )
print("q // 2 =", np.floor_divide(q,2), "\n" )  # floor division
print("-q     = ",np.negative(q), "\n" )
print("q ** 2 =", np.power(q, 2), "\n" )
print("q % 2 =",  np.mod(q,2 ), "\n" )

q     = [[ 1  3  5  7  9]
 [11 13 15 17 19]] 

q + 5 = [[ 6  8 10 12 14]
 [16 18 20 22 24]] 

q - 5 = [[-4 -2  0  2  4]
 [ 6  8 10 12 14]] 

q * 2 = [[ 2  6 10 14 18]
 [22 26 30 34 38]] 

q / 2 = [[0.5 1.5 2.5 3.5 4.5]
 [5.5 6.5 7.5 8.5 9.5]] 

q // 2 = [[0 1 2 3 4]
 [5 6 7 8 9]] 

-q     =  [[ -1  -3  -5  -7  -9]
 [-11 -13 -15 -17 -19]] 

q ** 2 = [[  1   9  25  49  81]
 [121 169 225 289 361]] 

q % 2 = [[1 1 1 1 1]
 [1 1 1 1 1]] 



In [32]:
# https://www.sharpsightlabs.com/blog/numpy-linspace/
theta = np.linspace(0, np.pi, 3)

In [33]:
theta

array([0.        , 1.57079633, 3.14159265])

In [34]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [35]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [36]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


# Advanced Ufunc Features

## Specifying output

In [38]:
x = np.arange(5)
y = np.empty(5)
print(y)
np.multiply(x, 10, out=y)
print(y)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[ 0. 10. 20. 30. 40.]


.. which can even be used with array views. For example, we can write the results of a computation to every other element of a specified array:

In [39]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


## Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [40]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [41]:
np.multiply.reduce(x)

120

In [42]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [43]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])